name: build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update && sudo apt -y install build-essential wget git libicu-dev libboost-iostreams-dev libgtest-dev libgmock-dev
      - run: cd /tmp && wget https://github.com/Kitware/CMake/releases/download/v3.21.5/cmake-3.21.5-linux-x86_64.sh && sudo sh cmake-3.21.5-linux-x86_64.sh --prefix=/usr --skip-license && rm cmake-3.21.5-linux-x86_64.sh
      - run: cd /tmp && git clone https://github.com/google/cityhash.git && cd cityhash && ./configure --enable-sse4.2 && make all check CXXFLAGS="-g -O3 -msse4.2" && sudo make install && cd .. && rm -rdf ./cityhash/
      - run: mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release .. && cmake --build . && cd ..
      - run: cd build/test && ctest
